export const ORDER_NEWS_SUCCESS = 'ORDER_NEWS_SUCCESS';
export const ORDER_NEWS_ID_SUCCESS = 'ORDER_NEWS_ID_SUCCESS';
export const ORDER_NEWS_REQUEST = 'ORDER_NEWS_REQUEST';
export const ORDER_NEWS_ERROR = 'ORDER_NEWS_ERROR';

export const ORDER_COMMENTS_SUCCESS = 'ORDER_COMMENTS_SUCCESS';